### ISSUE TITLE
Make Travis-CI Unit Tests Compatible with DeepDive v0.8.x Syntax

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#31]
Since making the switch to DeepDive v0.8.x, the syntax of the UDFs has changed, which has also caused our unit tests to not work:

```bash
ImportError: Failed to import test module: test.test_ext_part_nums
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/luke/repos/hwdeepdive/udf/test/test_ext_part_nums.py", line 13, in <module>
    from ext_part_nums import match_part_num_keywords
  File "/home/luke/repos/hwdeepdive/udf/ext_part_nums.py", line 21, in <module>
    from deepdive import *  # Required for @tsv_extractor and @returns
ImportError: No module named deepdive
```

Which is expected, since DeepDive isn't installed on the Travis-CI instance. I either need to figure out how to get it installed before each test, or figure out how to remove that dependency. Ideally, we can just remove the dependency because the unittests we are doing are just simple Python unit tests.

**Comment by lukehsiao** [comment]
Fixed in 3f810ee
